### ISSUE TITLE
Implement support for ECPP "classes" via zproject, and use that in this codebase

### ISSUE THREAD

**Issue by jimklimov** [42ity/fty-rest#361]
Current implementation per PR #351 uses our dirty hacks to represent ECPP servlets as if they were zproject-managed classes. This causes tracking many needless header files and adding some targets in a `Makemodule-local.am` (compilation, customized XML config generation - maybe with the servlet names and API URLs from project.xml, the `web-test` helper), as well as special overrides for packaging, rather than doing this as part of zproject generation logic.

This issue is to remind that such improvement to zproject and subsequent conversion of this component (and some others) would simplify our practice a lot.

**Comment by FrancoisRegisDegott-eaton** [comment]
deprecated
