### ISSUE TITLE
warranty-metric binary and service in different repos

### ISSUE THREAD

**Issue by jimklimov** [42ity/fty-rest#363]
The `warranty-metric` service is currently defined in `fty-core` while the source code and binary is part of `fty-rest`. It would make sense to deliver all parts of the component by the same repository.

**Comment by jimklimov** [comment]
Extracted into fty-warranty as a standalone component and service (last week), expelled from fty-core (today).

Remaining bit is to kill off the not-needed sources from fty-rest.

**Comment by jana-rapava** [comment]
Duplicate source code was deleted, I checked that warranty metrics are sent. Closing the issue.
