### ISSUE TITLE
Keep in mind : SASLAUTHD_MUX path support after zproject'ization

### ISSUE THREAD

**Issue by jimklimov** [42ity/fty-rest#371]
Old project structure allowed to define `SASLAUTHD_MUX` during build, so it could be overridden for tests or other distros (default is handled in C/C++/ECPP sources). It seems the results of #351 lack the ability to override it, but so far this is just a hunch.

**Comment by jimklimov** [comment]
Seems this (with `sasl.cc`) moved to fty-common. The m4 file `m4/bs_check_saslauthd_mux.m4` to set up the option remained in fty-rest - it should probably also move into fty-common now, and get called from the configure script to customize the path.

Revise packaging recipes of both to use/not-use the corresponding `configure` options.

**Comment by jimklimov** [comment]
Remaining TODO: Check in some distro detection of the path (needs a running SASLAUTHD daemon) and that the configured value is indeed honored by built binary.

**Comment by FrancoisRegisDegott-eaton** [comment]
deprecated
