### ISSUE TITLE
Refactor: consider moving unit-test programs under zproject paradigms

### ISSUE THREAD

**Issue by jimklimov** [42ity/fty-rest#427]
The legacy unit tests are managed with CATCH and are built separately. Perhaps move the code into selftest units as proposed by zproject habits. Note that the zeromq community currently evaluates using Unity (IIRC) to manage libzmq or czmq tests, so this may be a moving target to evaluate later.

**Comment by FrancoisRegisDegott-eaton** [comment]
deprecated
